# Generated by Django 4.2.11 on 2024-06-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='attraction_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
